### ISSUE TITLE
Clarifying proper motion requirement and general questions

### ISSUE THREAD

**Issue by tigikay** [PaulMcMillan-Astro/GalPot#1]
Hello Paul, 

Is the RA proper motion requested by the program just mu_alpha, or does the asterisk stand for something? Asking because I was wary that the asterisk might imply the need for mu_alpha*cos(delta)

Also, just so I can clear up two other questions (I intend to use your GalPot code for Gaia's DR2 and I thank you for the accessibility):

- Did you get an analytical potential for the 6 components in your latest model (and 2017 paper) or did GalPot numerically derive the potential for each set of parameters? I was hoping to get the potentials from your paper and apply them to my own N-body code.

- Is there a suggested number of Monte Carlo samples used and can the output be made worse by a larger than average number of n_tests?

**Comment by PaulMcMillan-Astro** [comment]
It's genuinely mu_alpha*, which is defined as cos(delta)*d alpha/dt. mu_alpha* is what Gaia DR2 will provide as pmra 

It's numerical, not analytical.

The number required depends on the application (and the data). I can't imagine a situation where the output is worse because of the higher number of n_tests.
